// Date: 8/17/2014 2:22:23 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.mcprog.greece.client.renderer.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

/**
 * 
 * @author mcprog
 * Generate by techne
 *
 */
public class ModelColumn extends ModelBase
{
  //fields
    ModelRenderer out1;
    ModelRenderer out2;
    ModelRenderer out3;
    ModelRenderer out4;
    ModelRenderer out5;
    ModelRenderer out6;
    ModelRenderer out7;
    ModelRenderer out8;
    ModelRenderer out9;
    ModelRenderer out10;
    ModelRenderer out11;
    ModelRenderer out12;
    ModelRenderer out13;
    ModelRenderer out14;
    ModelRenderer out15;
    ModelRenderer out16;
    ModelRenderer out17;
    ModelRenderer out18;
    ModelRenderer out19;
    ModelRenderer out20;
    ModelRenderer in1;
    ModelRenderer in2;
    ModelRenderer in3;
    ModelRenderer in4;
    ModelRenderer in5;
    ModelRenderer in6;
    ModelRenderer in7;
    ModelRenderer in8;
    ModelRenderer in9;
    ModelRenderer in10;
    ModelRenderer in11;
    ModelRenderer in12;
    ModelRenderer in13;
    ModelRenderer in14;
    ModelRenderer in15;
    ModelRenderer in16;
    ModelRenderer in17;
    ModelRenderer in18;
    ModelRenderer in19;
    ModelRenderer in20;
    ModelRenderer core;
  
  public ModelColumn()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      out1 = new ModelRenderer(this, 0, 0);
      out1.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out1.setRotationPoint(0F, 8F, 0F);
      out1.setTextureSize(64, 32);
      out1.mirror = true;
      setRotation(out1, 0F, 1.570796F, 0F);
      out2 = new ModelRenderer(this, 0, 0);
      out2.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out2.setRotationPoint(0F, 8F, 0F);
      out2.setTextureSize(64, 32);
      out2.mirror = true;
      setRotation(out2, 0F, 1.256637F, 0F);
      out3 = new ModelRenderer(this, 0, 0);
      out3.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out3.setRotationPoint(0F, 8F, 0F);
      out3.setTextureSize(64, 32);
      out3.mirror = true;
      setRotation(out3, 0F, 0.9424778F, 0F);
      out4 = new ModelRenderer(this, 0, 0);
      out4.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out4.setRotationPoint(0F, 8F, 0F);
      out4.setTextureSize(64, 32);
      out4.mirror = true;
      setRotation(out4, 0F, 0.6283185F, 0F);
      out5 = new ModelRenderer(this, 0, 0);
      out5.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out5.setRotationPoint(0F, 8F, 0F);
      out5.setTextureSize(64, 32);
      out5.mirror = true;
      setRotation(out5, 0F, 0.3141593F, 0F);
      out6 = new ModelRenderer(this, 0, 0);
      out6.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out6.setRotationPoint(0F, 8F, 0F);
      out6.setTextureSize(64, 32);
      out6.mirror = true;
      setRotation(out6, 0F, 0F, 0F);
      out7 = new ModelRenderer(this, 0, 0);
      out7.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out7.setRotationPoint(0F, 8F, 0F);
      out7.setTextureSize(64, 32);
      out7.mirror = true;
      setRotation(out7, 0F, -0.3141593F, 0F);
      out8 = new ModelRenderer(this, 0, 0);
      out8.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out8.setRotationPoint(0F, 8F, 0F);
      out8.setTextureSize(64, 32);
      out8.mirror = true;
      setRotation(out8, 0F, -0.6283185F, 0F);
      out9 = new ModelRenderer(this, 0, 0);
      out9.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out9.setRotationPoint(0F, 8F, 0F);
      out9.setTextureSize(64, 32);
      out9.mirror = true;
      setRotation(out9, 0F, -0.9424778F, 0F);
      out10 = new ModelRenderer(this, 0, 0);
      out10.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out10.setRotationPoint(0F, 8F, 0F);
      out10.setTextureSize(64, 32);
      out10.mirror = true;
      setRotation(out10, 0F, -1.256637F, 0F);
      out11 = new ModelRenderer(this, 0, 0);
      out11.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out11.setRotationPoint(0F, 8F, 0F);
      out11.setTextureSize(64, 32);
      out11.mirror = true;
      setRotation(out11, 0F, -1.570796F, 0F);
      out12 = new ModelRenderer(this, 0, 0);
      out12.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out12.setRotationPoint(0F, 8F, 0F);
      out12.setTextureSize(64, 32);
      out12.mirror = true;
      setRotation(out12, 0F, -1.884956F, 0F);
      out13 = new ModelRenderer(this, 0, 0);
      out13.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out13.setRotationPoint(0F, 8F, 0F);
      out13.setTextureSize(64, 32);
      out13.mirror = true;
      setRotation(out13, 0F, -2.199115F, 0F);
      out14 = new ModelRenderer(this, 0, 0);
      out14.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out14.setRotationPoint(0F, 8F, 0F);
      out14.setTextureSize(64, 32);
      out14.mirror = true;
      setRotation(out14, 0F, -2.513274F, 0F);
      out15 = new ModelRenderer(this, 0, 0);
      out15.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out15.setRotationPoint(0F, 8F, 0F);
      out15.setTextureSize(64, 32);
      out15.mirror = true;
      setRotation(out15, 0F, -2.827433F, 0F);
      out16 = new ModelRenderer(this, 0, 0);
      out16.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out16.setRotationPoint(0F, 8F, 0F);
      out16.setTextureSize(64, 32);
      out16.mirror = true;
      setRotation(out16, 0F, 3.141593F, 0F);
      out17 = new ModelRenderer(this, 0, 0);
      out17.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out17.setRotationPoint(0F, 8F, 0F);
      out17.setTextureSize(64, 32);
      out17.mirror = true;
      setRotation(out17, 0F, 2.827433F, 0F);
      out18 = new ModelRenderer(this, 0, 0);
      out18.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out18.setRotationPoint(0F, 8F, 0F);
      out18.setTextureSize(64, 32);
      out18.mirror = true;
      setRotation(out18, 0F, 2.513274F, 0F);
      out19 = new ModelRenderer(this, 0, 0);
      out19.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out19.setRotationPoint(0F, 8F, 0F);
      out19.setTextureSize(64, 32);
      out19.mirror = true;
      setRotation(out19, 0F, 2.199115F, 0F);
      out20 = new ModelRenderer(this, 0, 0);
      out20.addBox(-0.5F, 0F, -7F, 1, 16, 1);
      out20.setRotationPoint(0F, 8F, 0F);
      out20.setTextureSize(64, 32);
      out20.mirror = true;
      setRotation(out20, 0F, 1.884956F, 0F);
      in1 = new ModelRenderer(this, 4, 0);
      in1.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in1.setRotationPoint(0F, 8F, 0F);
      in1.setTextureSize(64, 32);
      in1.mirror = true;
      setRotation(in1, 0F, 1.413717F, 0F);
      in2 = new ModelRenderer(this, 4, 0);
      in2.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in2.setRotationPoint(0F, 8F, 0F);
      in2.setTextureSize(64, 32);
      in2.mirror = true;
      setRotation(in2, 0F, 1.099557F, 0F);
      in3 = new ModelRenderer(this, 4, 0);
      in3.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in3.setRotationPoint(0F, 8F, 0F);
      in3.setTextureSize(64, 32);
      in3.mirror = true;
      setRotation(in3, 0F, 0.7853982F, 0F);
      in4 = new ModelRenderer(this, 4, 0);
      in4.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in4.setRotationPoint(0F, 8F, 0F);
      in4.setTextureSize(64, 32);
      in4.mirror = true;
      setRotation(in4, 0F, 0.4712389F, 0F);
      in5 = new ModelRenderer(this, 4, 0);
      in5.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in5.setRotationPoint(0F, 8F, 0F);
      in5.setTextureSize(64, 32);
      in5.mirror = true;
      setRotation(in5, 0F, 0.1570796F, 0F);
      in6 = new ModelRenderer(this, 4, 0);
      in6.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in6.setRotationPoint(0F, 8F, 0F);
      in6.setTextureSize(64, 32);
      in6.mirror = true;
      setRotation(in6, 0F, -0.1570796F, 0F);
      in7 = new ModelRenderer(this, 4, 0);
      in7.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in7.setRotationPoint(0F, 8F, 0F);
      in7.setTextureSize(64, 32);
      in7.mirror = true;
      setRotation(in7, 0F, -0.4712389F, 0F);
      in8 = new ModelRenderer(this, 4, 0);
      in8.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in8.setRotationPoint(0F, 8F, 0F);
      in8.setTextureSize(64, 32);
      in8.mirror = true;
      setRotation(in8, 0F, -0.7853982F, 0F);
      in9 = new ModelRenderer(this, 4, 0);
      in9.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in9.setRotationPoint(0F, 8F, 0F);
      in9.setTextureSize(64, 32);
      in9.mirror = true;
      setRotation(in9, 0F, -1.099557F, 0F);
      in10 = new ModelRenderer(this, 4, 0);
      in10.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in10.setRotationPoint(0F, 8F, 0F);
      in10.setTextureSize(64, 32);
      in10.mirror = true;
      setRotation(in10, 0F, -1.413717F, 0F);
      in11 = new ModelRenderer(this, 4, 0);
      in11.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in11.setRotationPoint(0F, 8F, 0F);
      in11.setTextureSize(64, 32);
      in11.mirror = true;
      setRotation(in11, 0F, -1.727876F, 0F);
      in12 = new ModelRenderer(this, 4, 0);
      in12.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in12.setRotationPoint(0F, 8F, 0F);
      in12.setTextureSize(64, 32);
      in12.mirror = true;
      setRotation(in12, 0F, -2.042035F, 0F);
      in13 = new ModelRenderer(this, 4, 0);
      in13.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in13.setRotationPoint(0F, 8F, 0F);
      in13.setTextureSize(64, 32);
      in13.mirror = true;
      setRotation(in13, 0F, -2.356194F, 0F);
      in14 = new ModelRenderer(this, 4, 0);
      in14.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in14.setRotationPoint(0F, 8F, 0F);
      in14.setTextureSize(64, 32);
      in14.mirror = true;
      setRotation(in14, 0F, -2.670354F, 0F);
      in15 = new ModelRenderer(this, 4, 0);
      in15.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in15.setRotationPoint(0F, 8F, 0F);
      in15.setTextureSize(64, 32);
      in15.mirror = true;
      setRotation(in15, 0F, -2.984513F, 0F);
      in16 = new ModelRenderer(this, 4, 0);
      in16.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in16.setRotationPoint(0F, 8F, 0F);
      in16.setTextureSize(64, 32);
      in16.mirror = true;
      setRotation(in16, 0F, -3.298672F, 0F);
      in17 = new ModelRenderer(this, 4, 0);
      in17.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in17.setRotationPoint(0F, 8F, 0F);
      in17.setTextureSize(64, 32);
      in17.mirror = true;
      setRotation(in17, 0F, 2.670354F, 0F);
      in18 = new ModelRenderer(this, 4, 0);
      in18.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in18.setRotationPoint(0F, 8F, 0F);
      in18.setTextureSize(64, 32);
      in18.mirror = true;
      setRotation(in18, 0F, 2.356194F, 0F);
      in19 = new ModelRenderer(this, 4, 0);
      in19.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in19.setRotationPoint(0F, 8F, 0F);
      in19.setTextureSize(64, 32);
      in19.mirror = true;
      setRotation(in19, 0F, 2.042035F, 0F);
      in20 = new ModelRenderer(this, 4, 0);
      in20.addBox(-1F, 0F, -6.5F, 2, 16, 2);
      in20.setRotationPoint(0F, 8F, 0F);
      in20.setTextureSize(64, 32);
      in20.mirror = true;
      setRotation(in20, 0F, 1.727876F, 0F);
      core = new ModelRenderer(this, 12, 0);
      core.addBox(-4.5F, 0F, -4.5F, 9, 16, 9);
      core.setRotationPoint(0F, 8F, 0F);
      core.setTextureSize(64, 32);
      core.mirror = true;
      setRotation(core, 0F, 0.1570796F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    out1.render(f5);
    out2.render(f5);
    out3.render(f5);
    out4.render(f5);
    out5.render(f5);
    out6.render(f5);
    out7.render(f5);
    out8.render(f5);
    out9.render(f5);
    out10.render(f5);
    out11.render(f5);
    out12.render(f5);
    out13.render(f5);
    out14.render(f5);
    out15.render(f5);
    out16.render(f5);
    out17.render(f5);
    out18.render(f5);
    out19.render(f5);
    out20.render(f5);
    in1.render(f5);
    in2.render(f5);
    in3.render(f5);
    in4.render(f5);
    in5.render(f5);
    in6.render(f5);
    in7.render(f5);
    in8.render(f5);
    in9.render(f5);
    in10.render(f5);
    in11.render(f5);
    in12.render(f5);
    in13.render(f5);
    in14.render(f5);
    in15.render(f5);
    in16.render(f5);
    in17.render(f5);
    in18.render(f5);
    in19.render(f5);
    in20.render(f5);
    core.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
